### ISSUE TITLE
Can't get $HOME into ~

### ISSUE THREAD

**Issue by georgeguimaraes** [ofirgall/tmux-window-name#28] opened 2023-05-22 14:52 UTC
Hi, tks for the plugin. It's really helping me get into tmux and organizing all my windows.

I'm trying to get my home dir translated into ~ but can't get it working. Even tried to set @tmux_window_name_dir_substitute_sets as follow:

```
set -g @plugin 'ofirgall/tmux-window-name'
set -g @tmux_window_name_use_tilde "True"
set -g @tmux_window_name_dir_substitute_sets "[('/Users/george', '~')]"
```

I'm using macOS here. 

Also, I tried to change the plugin source code directly:

```
diff --git a/scripts/rename_session_windows.py b/scripts/rename_session_windows.py
index ce9a84e..99f2a8c 100755
--- a/scripts/rename_session_windows.py
+++ b/scripts/rename_session_windows.py
@@ -117,9 +117,9 @@ class Options:
     dir_programs: List[str] = field(default_factory=lambda: ['nvim', 'vim', 'vi', 'git'])
     ignored_programs: List[str] = field(default_factory=lambda: [])
     max_name_len: int = 20
-    use_tilde: bool = False
+    use_tilde: bool = True
     substitute_sets: List[Tuple] = field(default_factory=lambda: [('.+ipython([32])', r'ipython\g<1>'), (r'^(/usr)?/bin/(.+)', r'\g<2>'), ('(bash) (.+)/(.+[ $])(.+)', '\g<3>\g<4>')])
-    dir_substitute_sets: List[Tuple] = field(default_factory=lambda: [])
+    dir_substitute_sets: List[Tuple] = field(default_factory=lambda: [('/Users/george', '~')])
 
     @staticmethod
     def from_options(server: Server):
```

but still got `george` instead of `˜`:
![CleanShot 2023-05-22 at 11 51 29](https://github.com/ofirgall/tmux-window-name/assets/2929/f6e5b200-b53a-455c-9728-60be35533c84)

Any way to debug this further? I'm not good at Python code.

**Comment by georgeguimaraes** [comment] 2023-05-23 17:39
Sure:

```
❯ pwd
/Users/george
❯ echo $HOME
/Users/george
❯ ~/.tmux/plugins/tmux-window-name/scripts/rename_session_windows.py --print_programs
nvim -> nvim
nvim -> nvim
```

![CleanShot 2023-05-23 at 14 38 48](https://github.com/ofirgall/tmux-window-name/assets/2929/dc07ee60-0a0c-46ad-8806-244c7a24da81)

**Comment by georgeguimaraes** [comment] 2023-05-23 17:42
(I've also reverted my changes to the python script before running the program above)

**Comment by ofirgall** [comment] 2023-09-12 12:19
Hey, sorry for the late response, I have added logs for the plugin, update the plugin and set the log level to debug by `set -g @tmux_window_name_log_level "'DEBUG'"`.

The logs are going to `/tmp/tmux-window-name`, please share them.

**Comment by thepante** [comment] 2023-10-10 15:08
Hi, i handled to get a fix (? I don't know. Didn't so much testing other that the basic.
The problem I saw there is that when it tried to update `$HOME` to `~` it didn't match because there already got the _display name_ as value (so the username only, not the home path that should contain the matching string).

So i hardcoded like this:
```
M scripts/path_utils.py
@@ -70,6 +70,9 @@ def get_exclusive_paths(panes: List[Pane]) -> List[Tuple[Pane, Path]]:
             if panes[x].program != panes[y].program:
                 continue
 
+            if str(exc_paths[x].full) == '/Users/fabian' and exc_paths[x].display:
+                exc_paths[x].display = exc_paths[x].full
+
             # If full path equals no need to find a display path
             if exc_paths[x].full == exc_paths[y].full:
                 same_paths_different_programs.append(y)
```

Now it is working the option to use tilde when is the home path. Before and after:

![SCR-20231010-fnn](https://github.com/ofirgall/tmux-window-name/assets/10443522/36d77fc0-4643-4869-a167-df32f09db5c3)
![SCR-20231010-g7v](https://github.com/ofirgall/tmux-window-name/assets/10443522/da791003-6a6e-4353-bb1c-59f208569056)

I didn't send pull request because i don't know if that way is a proper solution (updating the display value with the full one).

**Comment by ofirgall** [comment] 2023-10-13 10:54
Hey @thepante , thanks for the debugging but I think `get_exclusive_paths` isn't the right place to fix the problem,

I can't reproduce the issue on my machines, can you turn on the debug feature and send the logs?

**Comment by thepante** [comment] 2023-10-13 12:15
Sure, here's a short test:

```bash
DEBUG - rename_session_windows.py:316 main() Args: Namespace(print_programs=False, enable_rename_hook=False, disable_rename_hook=False, post_restore=False)
DEBUG - rename_session_windows.py:317 main() Options: Options(shells=['bash', 'fish', 'sh', 'zsh'], dir_programs=['nvim', 'vim', 'vi', 'git'], ignored_programs=[], max_name_len=20, use_tilde=True, substitute_sets=[('.+ipython([32])', 'ipython\\g<1>'), ('^(/usr)?/bin/(.+)', '\\g<2>'), ('(bash) (.+)/(.+[ $])(.+)', '\\g<3>\\g<4>')], dir_substitute_sets=[], log_level='DEBUG')
DEBUG - rename_session_windows.py:237 rename_windows() panes_with_programs=[]
DEBUG - rename_session_windows.py:238 rename_windows() panes_with_dir=[Pane(info=Pane(%13 Window(@12 0:Documents, Session($1 4))), program=None), Pane(info=Pane(%11 Window(@10 3:Downloads, Session($1 4))), program=None), Pane(info=Pane(%12 Window(@11 4:tmux-window-name, Session($1 4))), program=None)]
DEBUG - rename_session_windows.py:265 rename_windows() processing exclusive_path: display_path=PosixPath('Documents') p.program=None
DEBUG - rename_session_windows.py:278 substitute_name() substituting Documents
DEBUG - rename_session_windows.py:200 rename_window() renaming window_id='@12' to window_name='Documents'
DEBUG - rename_session_windows.py:203 rename_window() replaced tilde with HOME_DIR='/Users/fabian': window_name='Documents'
DEBUG - rename_session_windows.py:206 rename_window() shortened name window_name='Documents'
DEBUG - rename_session_windows.py:265 rename_windows() processing exclusive_path: display_path=PosixPath('fabian') p.program=None
DEBUG - rename_session_windows.py:278 substitute_name() substituting fabian
DEBUG - rename_session_windows.py:200 rename_window() renaming window_id='@10' to window_name='fabian'
DEBUG - rename_session_windows.py:203 rename_window() replaced tilde with HOME_DIR='/Users/fabian': window_name='fabian'
DEBUG - rename_session_windows.py:206 rename_window() shortened name window_name='fabian'
DEBUG - rename_session_windows.py:265 rename_windows() processing exclusive_path: display_path=PosixPath('tmux-window-name') p.program=None
DEBUG - rename_session_windows.py:278 substitute_name() substituting tmux-window-name
DEBUG - rename_session_windows.py:200 rename_window() renaming window_id='@11' to window_name='tmux-window-name'
DEBUG - rename_session_windows.py:203 rename_window() replaced tilde with HOME_DIR='/Users/fabian': window_name='tmux-window-name'
DEBUG - rename_session_windows.py:206 rename_window() shortened name window_name='tmux-window-name'
```

Could it be something related to how python is getting the absolute path?
Because, maybe related, this is how I did to found the log file, because it wasn't at `/tmp/`:

```bash
 » python3
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, tempfile
>>> print(os.path.join(tempfile.gettempdir(), 'tmux-window-name'))
/var/folders/pj/mkk21rt16rjf_pnl4gfjlydm0000gn/T/tmux-window-name
```

**Comment by ofirgall** [comment] 2023-10-13 13:06
Thanks @thepante, your first change was in the right direction but in the wrong place, I pushed a commit that replacing the tilde with the full path and not the final result.
Can you check if it fixes the problem for your?

**Comment by thepante** [comment] 2023-10-13 16:51
Great! Now it's working perfect 😃
Thank you!

**Comment by ofirgall** [comment] 2023-10-15 16:20
Great, I close this issue.
@georgeguimaraes feel free to re-open the issue if it's still occurs to you

**Closed by ofirgall** 2023-10-15 16:20 UTC
