### ISSUE TITLE
Cannot get it to work preperly

### ISSUE THREAD

**Issue by sandrodz** [ofirgall/tmux-window-name#26] opened 2023-02-21 05:54 UTC
Hi, I think I am missing something in configuration here.

if I've running command name appears, see docker compose up:

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/8479569/220259052-e77a1629-8b79-4a02-ac55-5e4b669fc032.png">

but if I navigate back to docker tab as you can see directory/project is not visible in the other window:

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/8479569/220259243-37c9139c-48f5-45c0-b881-b2f7b100936a.png">

**Comment by ofirgall** [comment] 2023-02-21 08:11
Hey, it seems like the plugin isn't installed/activated.
How did you installed the plugin?
If it was successfully installed there should be a `tmux-window-name` directory at `$TMUX_PLUGIN_MANAGER_PATH` which is usually configured to `~/.tmux/plugins`

**Comment by sandrodz** [comment] 2023-02-21 09:11
@ofirgall sure its there:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/8479569/220300137-0ccf2ddd-8a2e-4e7f-bc96-6c28a3462dc9.png">

I installed it like this:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/8479569/220300244-5dc1e904-70e3-4c8f-a6ee-b98ccf81cdd8.png">

**Comment by ofirgall** [comment] 2023-02-21 09:28
Can you run `tmux show-hooks -g | grep tmux-window-name` to check if the hooks are activated?
Also can you run `~/.tmux/plugins/tmux-window-name/scripts/rename_session_windows.py` manually to test if the rename script works?

**Comment by sandrodz** [comment] 2023-02-21 09:29
<img width="771" alt="image" src="https://user-images.githubusercontent.com/8479569/220304725-267062b8-c901-4c63-99b5-118c9984ea48.png">

when I run `~/.tmux/plugins/tmux-window-name/scripts/rename_session_windows.py` nothing prints

**Comment by ofirgall** [comment] 2023-02-21 10:16
Great `rename_session_windows.py` seems to be working (it doesn't print on success), did it rename your windows?

What is the version of your tmux?

**Comment by sandrodz** [comment] 2023-02-21 14:07
It didn't rename anything :(

I've tmux-3.3a

**Comment by ofirgall** [comment] 2023-02-21 17:06
Whats the output of `~/.tmux/plugins/tmux-window-name/scripts/rename_session_windows.py --print_programs`?

**Comment by sandrodz** [comment] 2023-02-22 05:43
<img width="699" alt="image" src="https://user-images.githubusercontent.com/8479569/220533385-5c12c24a-7eb2-4710-a7ab-fbea3757fe4f.png">

could this be a problem:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/8479569/220533457-2317b317-a6f0-4e81-b550-b5f68689e7e7.png">

tried deleting seems not to have helped.

**Comment by ofirgall** [comment] 2023-02-22 17:08
Try to reset the window name by executing `tmux rename-window ""`

**Comment by sandrodz** [comment] 2023-02-22 18:51
When I do rename, something weird happens.

I do this in first window:
<img width="1207" alt="Screenshot 2023-02-22 at 22 50 26" src="https://user-images.githubusercontent.com/8479569/220729534-46d66910-f653-49d1-b870-d885071752ca.png">

switch to new window:
<img width="1207" alt="Screenshot 2023-02-22 at 22 50 33" src="https://user-images.githubusercontent.com/8479569/220729626-ab6e7065-03d5-4ea2-b3ef-b2ef627bbf42.png">

as you can see it shows command I ran in previous window, but after few seconds it goes back to `0 -zsh`

**Comment by ofirgall** [comment] 2023-02-26 07:09
It still seems the plugin doesn't work :( honestly I'm out of ideas. I don't think it would help but did you try to restart the tmux server?

**Comment by sandrodz** [comment] 2023-02-26 14:49
I tried restart. I am also using iterm2, maybe its messing with settings.

Would giving you my tmux config help?

**Comment by ofirgall** [comment] 2023-02-26 16:07
I'm not familiar with iterm2 behavior, but it might be the issue, can you try use the same tmux config with different terminal (kitty/alacritty/wezterm)?

It can be helpful.

**Comment by sandrodz** [comment] 2023-02-26 20:25
I tried kitty as I had it laying around, same :(

**Comment by jsvisa** [comment] 2023-07-18 08:33
I met a similar issue, after some debug, found the cause of the problem:

I install the `libtmux` package in a custom python environment, but tmux uses the system's python binary, so it can't import the `libtmux` packages.

Then I add my custom python environment in the `tmux.conf`, eg:

```
set-environment -g PATH "$HOME/.miniconda3/bin/:/usr/local/bin:/bin:/usr/bin"
```

**Comment by akhiljalagam** [comment] 2023-08-21 14:22
Could someone share their working tmux.conf?

**Comment by ofirgall** [comment] 2023-09-12 12:18
Hey, sorry for the late response, I have added logs for the plugin, update the plugin and set the log level to debug by `set -g @tmux_window_name_log_level "'DEBUG'"`.

The logs are going to `/tmp/tmux-window-name`, please share them.

**Comment by ofirgall** [comment] 2023-10-13 12:01
Hey @Susensio how do you run your fish shell?
Did you set `set -g default-shell /usr/bin/fish` in your tmux config?

**Comment by Susensio** [comment] 2023-10-13 16:44
> Hey @Susensio how do you run your fish shell?
> Did you set `set -g default-shell /usr/bin/fish` in your tmux config?

I have my shell configured as `default-command`, idk if it makes a difference. I think I did it that way to avoid spawning a login shell but I don't recall for sure.
Anyway if I `display-message "#{default-shell}` tmux shows it's `/usr/bin/fish` although not explicitly set in config.

**Comment by ofirgall** [comment] 2023-10-19 07:54
Hey @Susensio I pushed a commit that should fix your problem, can you update the plugin and check it fixed your problem?

**Comment by ofirgall** [comment] 2023-11-16 18:17
I close the issue for now, feel free to leave a message to re-open.

**Closed** 2023-11-16 18:18 UTC

**Comment by TiLopes** [comment] 2024-01-30 13:15
I'm also facing the same issue. I see in my logs a line that might be the problem but I don't know what to do to fix it.
```
DEBUG - rename_session_windows.py:324 main() Args: Namespace(print_programs=False, enable_rename_hook=False, disable_rename_hook=False, post_restore=False)
DEBUG - rename_session_windows.py:325 main() Options: Options(shells=['bash', 'fish', 'sh', 'zsh'], dir_programs=['nvim', 'vim', 'vi', 'git'], ignored_programs=[], max_name_len=20, use_tilde=False, substitute_sets=[('.+ipython([32])', 'ipython\\\\g<1>'), ('^(/usr)?/bin/(.+)', '\\g<2>'), ('(bash) (.+)/(.+[ $])(.+)', '\\g<3>\\g<4>')], dir_substitute_sets=[], log_level='DEBUG')
DEBUG - rename_session_windows.py:232 rename_windows() panes_with_programs=[]
DEBUG - rename_session_windows.py:233 rename_windows() panes_with_dir=[Pane(info=Pane(%0 Window(@0 0:fish, Session($0 0))), program=None), Pane(info=Pane(%1 Window(@1 1:fish, Session($0 0))), program=None)]
DEBUG - rename_session_windows.py:253 rename_windows() get_exclusive_paths result, input: panes_with_dir=[Pane(info=Pane(%0 Window(@0 0:fish, Session($0 0))), program=None), Pane(info=Pane(%1 Window(@1 1:fish, Session($0 0))), program=None)], output: exclusive_paths=[(Pane(info=Pane(%0 Window(@0 0:fish, Session($0 0))), program=None), PosixPath('.config')), (Pane(info=Pane(%1 Window(@1 1:fish, Session($0 0))), program=None), PosixPath('xou'))]
DEBUG - rename_session_windows.py:261 rename_windows() processing exclusive_path: display_path=.config p.program=None
DEBUG - rename_session_windows.py:287 substitute_name() substituting .config
DEBUG - rename_session_windows.py:201 rename_window() renaming window_id=@0 to window_name=.config
DEBUG - rename_session_windows.py:204 rename_window() shortened name window_name=.config
DEBUG - rename_session_windows.py:258 rename_windows() tmux winodw isnt enabled in @1
```
It only changes when I move between windows otherwise nothing changes regardless of the path I'm in and the program I open (e.g nvim).
What is the `tmux window isn't enabled @1`?

**Comment by ofirgall** [comment] 2024-01-30 14:14
@TiLopes  It means the plugin is disabled for this window.

Did you rename the window manually? You can re-enable the plugin by renaming the window to none `tmux rename-window ""`.

**Comment by TiLopes** [comment] 2024-01-30 14:48
I never manually rename any window I simple create one using <prefix> c (the default keybinding).
This is my `tmux.conf`:
```
set -g default-shell /usr/bin/fish

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'niksingh710/minimal-tmux-status'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# PLUGINS SETTINGS
set -g @tmux_window_name_shells "['bash', 'fish', 'sh', 'zsh']"
set -g @tmux_window_name_max_name_len "20"
#

set -g mouse on
set -g default-terminal "screen-256color"

setw -g xterm-keys on
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on

set -g prefix2 C-a                        # GNU-Screen compatible prefix
bind C-a send-prefix -2

set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on

set -g history-limit 5000                 # boost history

set -g automatic-rename off
set -g renumber-windows on
set -g set-titles on

# create session
bind C-c new-session

# find session
bind C-f command-prompt -p find-session 'switch-client -t %%'

# session navigation
bind BTab switch-client -l  # move to last session

# split current window horizontally
bind - split-window -v
# split current window vertically
bind _ split-window -h

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window
```

**Comment by ofirgall** [comment] 2024-01-30 19:47
@TiLopes You set `automatic-rename` to off after initializing the tmux-window-name which sets it on, you need to remove this line.

**Comment by TiLopes** [comment] 2024-01-30 20:31
I removed the line yet it still does not work. When i open neovim it only says nvim but after I go to another window and back it changes to the correct name (nvim:folder).

I recorded a video to better show it.

https://github.com/ofirgall/tmux-window-name/assets/106965010/6f5670cd-eeaf-4349-820c-d77eb081b068

**Comment by ofirgall** [comment] 2024-02-01 16:56
@TiLopes This is the intended behaviour, I don't want to refresh the window names non stop in the background. I hook to tmux on window selected instead.

But you got me thinking about how renaming windows after neovim launch and autocmd came in mind. You can add the following code to your neovim configuration:
```lua
local uv = vim.loop

vim.api.nvim_create_autocmd('VimEnter', {
	callback = function()
		uv.spawn(vim.env.TMUX_PLUGIN_MANAGER_PATH .. '/tmux-window-name/scripts/rename_session_windows.py', {})
	end,
})
```
(I added the example to the README as well)
